.PHONY: up down stop

# Starts the docker containers in detached mode
up:
	docker compose up -d

# Stops and removes the docker containers, networks, and images created by up
down:
	docker compose down

# Stops running docker containers without removing them
stop:
	docker compose stop
